In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Contacts.csv')

In [3]:
df = df.rename(index=str, columns={'contact_id': 'Contact_id'})
name_df = df.iloc[:, 0:4]

In [4]:
df

,Contact_id,first_name,middle_name,last_name,home_phone,cell_phone,home_address,home_city,home_state,home_zip,work_phone,work_address,work_city,work_state,work_zip,birth_date
0,1,Cindra,Del,Philipeaux,NaN,732-392-7165,NaN,NaN,NaN,75018.0,575-780-6421,90103 Glacier Hill Terrace,Plano,Texas,75003.0,NaN
1,2,Sherwood,NaN,Spoerl,441-557-2835,907-913-3698,2287 Sutteridge Park,Dallas,Texas,75062.0,526-691-3663,37 Sommers Hill,Addison,Texas,75006.0,1986-06-07
2,3,Crosby,NaN,Seide,998-239-4082,637-715-3867,NaN,NaN,NaN,75029.0,470-347-7202,NaN,NaN,NaN,NaN,1965-06-23
3,4,Hogan,NaN,Spafford,NaN,359-747-1907,NaN,NaN,NaN,75099.0,NaN,3 Mccormick Parkway,Allen,Texas,75008.0,NaN
4,5,Kenton,Rog,Sibbald,317-756-0975,543-710-0843,62477 Hovde Hill,Allen,Texas,75061.0,672-643-5210,35836 Banding Way,Richardson,Texas,75004.0,1972-05-11
5,6,Brand,Melisande,Morkham,NaN,227-992-2900,06 Heffernan Center,Richardson,Texas,NaN,935-221-4565,44 Farragut Avenue,Addison,Texas,75009.0,1984-08-19
6,7,Adina,NaN,Richardon,NaN,181-781-9784,NaN,NaN,NaN,75031.0,NaN,NaN,NaN,NaN,NaN,NaN
7,8,Maddalena,Ettore,O' Hern,NaN,871-791-7851,16515 Nova Hill,Allen,Texas,75041.0,420-902-8960,363 Truax Trail,Addison,Texas,75005.0,NaN
8,9,Claus,NaN,Gensavage,NaN,933-257-7616,626 Orin Center,Addison,Texas,NaN,536-596-8574,17 Clyde Gallagher Alley,Richardson,Texas,75007.0,NaN
9,10,Antonia,NaN,Wolstencroft,449-971-7759,747-303-4705,6687 Dottie Plaza,Richardson,Texas,75027.0,405-746-6553,NaN,NaN,NaN,NaN,NaN
10,11,Doll,Cristy,Kill,790-832-4539,423-257-0444,8 Luster Terrace,Dallas,Texas,75059.0,NaN,NaN,NaN,NaN,NaN,1987-05-13
11,12,Maritsa,Priscilla,Tinsey,812-671-2569,537-987-3004,NaN,NaN,NaN,75076.0,974-398-8066,NaN,NaN,NaN,NaN,1994-09-15
12,13,Ward,Nellie,Shackell,NaN,994-189-5386,15 Jackson Lane,Allen,Texas,75013.0,NaN,8705 West Junction,Addison,Texas,75008.0,1974-11-26
13,14,Cybill,Sissie,Ratazzi,454-730-8259,223-746-7737,79254 Pond Center,Dallas,Texas,75083.0,NaN,NaN,NaN,NaN,NaN,1993-12-01
14,15,Harriet,Herminia,Swin,NaN,769-740-9664,9 Logan Parkway,Dallas,Texas,75078.0,944-146-6149,NaN,NaN,NaN,NaN,1986-12-30
15,16,Homerus,NaN,Dugood,629-438-4169,275-477-5499,65052 Heath Point,Plano,Texas,75046.0,100-718-3343,NaN,NaN,NaN,NaN,NaN
16,17,Reuven,NaN,Capstaff,804-209-6009,272-367-4116,NaN,NaN,NaN,75005.0,NaN,3522 Butternut Place,Plano,Texas,75001.0,NaN
17,18,Lilian,NaN,Perrin,NaN,770-282-5502,8 Fuller Road,Addison,Texas,75088.0,725-135-7813,NaN,NaN,NaN,NaN,NaN
18,19,Dorey,Katheryn,Seamons,NaN,131-155-6846,1961 Division Hill,Addison,Texas,NaN,373-829-6128,NaN,NaN,NaN,NaN,NaN
19,20,Emmie,Bennie,Dust,NaN,452-967-2050,NaN,NaN,NaN,75042.0,205-867-7790,51819 Donald Trail,Richardson,Texas,75002.0,NaN
20,21,Palm,NaN,Tuhy,NaN,310-517-1998,NaN,NaN,NaN,75060.0,136-209-9292,NaN,NaN,NaN,NaN,NaN
21,22,Jakie,Eddy,Muehle,130-493-8381,905-442-0240,528 Main Junction,Dallas,Texas,75046.0,732-735-8158,3715 Muir Park,Dallas,Texas,75005.0,NaN
22,23,Torin,NaN,McHaffy,234-782-3406,886-702-1908,9086 Sommers Crossing,Richardson,Texas,NaN,NaN,4 Emmet Junction,Plano,Texas,75004.0,1986-06-11
23,24,Bjorn,NaN,Crathorne,387-995-2640,562-617-1312,NaN,NaN,NaN,75099.0,364-839-7318,NaN,NaN,NaN,NaN,1996-04-27
24,25,Mariana,Ebenezer,Titmarsh,NaN,873-511-6075,83 Shoshone Parkway,Plano,Texas,75046.0,754-815-2133,2 Lillian Drive,Addison,Texas,75001.0,1979-12-31
25,26,Clemmy,NaN,Widdup,NaN,826-297-4157,333 Scoville Hill,Allen,Texas,75091.0,NaN,6 Michigan Pass,Dallas,Texas,75004.0,1994-02-25
26,27,Darrell,Egon,Lokier,NaN,770-453-6125,18894 Division Lane,Richardson,Texas,75083.0,205-324-5139,2408 Riverside Parkway,Plano,Texas,75007.0,1979-06-09
27,28,Thornton,NaN,Kennaird,NaN,806-105-9954,250 2nd Drive,Richardson,Texas,NaN,742-339-9060,NaN,NaN,NaN,NaN,1978-11-06
28,29,Philip,Jaquith,Edworthye,388-488-7596,899-522-4338,85701 Basil Road,Allen,Texas,75004.0,570-895-9983,NaN,NaN,NaN,NaN,NaN
29,30,Dud,NaN,Harvison,744-544-2543,993-228-0137,23 Kings Lane,Plano,Texas,75086.0,NaN,NaN,NaN,NaN,NaN,1974-09-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,971,Asher,NaN,Wasselin,NaN,350-773-0890,5452 Walton Junction,Richardson,Texas,75074.0,727-591-4194,NaN,NaN,NaN,NaN,NaN
971,972,Ninnetta,Vitia,Heasman,236-716-1495,805-597-6743,22 Dwight Center,Addison,Texas,75033.0,474-611-4311,NaN,NaN,NaN,NaN,1980-12-18
972,973,Cecilius,NaN,Popelay,NaN,338-961-3558,9 Kim Alley,Plano,Texas,75083.0,281-163-7057,NaN,NaN,NaN,NaN,NaN
973,974,Rhetta,Lisle,Hall-Gough,611-473-9520,501-940-1523,17 Killdeer Parkway,Addison,Texas,75087.0,513-590-6081,553 Sycamore Way,Dallas,Texas,75001.0,1970-04-29
974,975,Elsinore,NaN,Cretney,118-808-6105,684-423-9257,70338 Clyde Gallagher Street,Dallas,Texas,75036.0,911-135-9814,0059 Hoepker Place,Richardson,Texas,75009.0,NaN
975,976,Annis,Chevalier,Zum Felde,444-807-2663,213-779-9815,204 Caliangt Way,Dallas,Texas,75049.0,725-849-3877,89641 Kings Place,Addison,Texas,75001.0,NaN
976,977,Merrel,Roberto,Sillwood,189-943-3809,814-757-2525,NaN,NaN,NaN,NaN,916-120-2308,8 Hoepker Lane,Plano,Texas,75001.0,1985-01-08
977,978,Boy,Reeva,Elwyn,627-850-8581,722-225-7767,7637 Burrows Alley,Addison,Texas,75085.0,680-399-1077,NaN,NaN,NaN,NaN,NaN
978,979,Bryna,NaN,Vaskov,NaN,727-717-8575,NaN,NaN,NaN,75001.0,509-326-1544,36884 Milwaukee Street,Dallas,Texas,75007.0,NaN
979,980,Brad,Sallyann,Clell,NaN,603-661-8661,0 Colorado Way,Richardson,Texas,NaN,885-458-7049,NaN,NaN,NaN,NaN,1985-08-15
980,981,Salomi,NaN,Stockin,NaN,584-623-3883,07151 Anderson Trail,Allen,Texas,75079.0,195-829-1027,501 Valley Edge Park,Richardson,Texas,75009.0,1976-03-05
981,982,Der,NaN,Scarlan,NaN,133-729-1440,0 Annamark Alley,Allen,Texas,75098.0,153-854-4154,NaN,NaN,NaN,NaN,1978-03-01
982,983,Shannen,Anna,Purselow,NaN,404-917-0949,5 Coleman Lane,Dallas,Texas,75001.0,NaN,NaN,NaN,NaN,NaN,1992-05-17
983,984,Lilith,Alejandro,Childerhouse,164-120-1050,559-290-1726,853 5th Terrace,Richardson,Texas,NaN,554-290-9935,NaN,NaN,NaN,NaN,1983-02-25
984,985,Karita,Brice,Risbridge,NaN,882-789-1124,46789 Moulton Crossing,Addison,Texas,75099.0,935-280-2452,2 Elgar Place,Plano,Texas,75006.0,1972-12-10
985,986,Rosaline,NaN,Bowker,NaN,643-101-9733,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1970-04-02
986,987,Joey,NaN,Burt,NaN,713-594-7295,1 Thierer Drive,Richardson,Texas,75017.0,603-266-1070,161 Katie Drive,Addison,Texas,75009.0,1978-08-17
987,988,Marjory,NaN,Holgan,194-870-5733,984-335-4433,7 Brown Hill,Addison,Texas,75077.0,998-707-5639,86 Meadow Vale Park,Plano,Texas,75001.0,NaN
988,989,Adler,Urban,Beake,NaN,916-995-4675,8 Huxley Junction,Plano,Texas,75029.0,NaN,NaN,NaN,NaN,NaN,NaN
989,990,Jon,Danni,Bolley,NaN,125-555-5586,70 Del Mar Junction,Plano,Texas,75062.0,NaN,0 Lillian Alley,Addison,Texas,75005.0,NaN
990,991,Shawn,NaN,Whetland,NaN,315-727-4644,5228 Commercial Crossing,Allen,Texas,NaN,569-411-8436,67 Continental Hill,Dallas,Texas,75008.0,NaN
991,992,Rhodie,Cross,Stovine,NaN,630-956-5252,5 Blue Bill Park Street,Plano,Texas,75003.0,914-785-8696,72701 Morningstar Way,Dallas,Texas,75005.0,NaN
992,993,Raimondo,NaN,Hubbard,NaN,871-510-0110,51469 Becker Point,Dallas,Texas,75014.0,NaN,NaN,NaN,NaN,NaN,1989-05-15
993,994,Darcey,NaN,Paolazzi,597-896-7953,281-491-8104,583 Manufacturers Avenue,Richardson,Texas,NaN,644-184-8850,38 Shoshone Terrace,Dallas,Texas,75006.0,1996-02-05
994,995,Carlos,Jessy,Barsam,456-537-7814,499-711-1417,0648 Lakewood Street,Plano,Texas,75006.0,929-545-6545,NaN,NaN,NaN,NaN,1971-07-05
995,996,Zared,Alan,Fontell,121-713-2260,511-907-3315,13 Main Way,Addison,Texas,75089.0,878-331-9664,46412 Vahlen Park,Addison,Texas,75007.0,1995-12-31
996,997,Janeta,NaN,Showers,311-345-4648,273-728-1271,782 Lighthouse Bay Pass,Allen,Texas,75060.0,NaN,3 Pennsylvania Terrace,Addison,Texas,75009.0,NaN
997,998,Carlen,NaN,Bickle,NaN,220-911-1306,008 Ryan Center,Plano,Texas,NaN,266-423-8899,67720 Myrtle Parkway,Dallas,Texas,75005.0,1993-03-07
998,999,Selie,Susana,Dahl,NaN,470-418-2608,5729 Farragut Plaza,Dallas,Texas,75079.0,290-423-8165,NaN,NaN,NaN,NaN,1977-08-12
999,1000,Adina,NaN,Demougeot,851-955-4193,952-976-4138,18201 Novick Circle,Richardson,Texas,75037.0,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
name_df.columns = ['Contact_id', 'Fname', 'Mname', 'Lname']

In [6]:
name_df

     Contact_id      Fname      Mname         Lname
0             1     Cindra        Del    Philipeaux
1             2   Sherwood        NaN        Spoerl
2             3     Crosby        NaN         Seide
3             4      Hogan        NaN      Spafford
4             5     Kenton        Rog       Sibbald
5             6      Brand  Melisande       Morkham
6             7      Adina        NaN     Richardon
7             8  Maddalena     Ettore       O' Hern
8             9      Claus        NaN     Gensavage
9            10    Antonia        NaN  Wolstencroft
10           11       Doll     Cristy          Kill
11           12    Maritsa  Priscilla        Tinsey
12           13       Ward     Nellie      Shackell
13           14     Cybill     Sissie       Ratazzi
14           15    Harriet   Herminia          Swin
15           16    Homerus        NaN        Dugood
16           17     Reuven        NaN      Capstaff
17           18     Lilian        NaN        Perrin
18           19      Dorey   Katheryn       Seamons
19           20      Emmie     Bennie          Dust
20           21       Palm        NaN          Tuhy
21           22      Jakie       Eddy        Muehle
22           23      Torin        NaN       McHaffy
23           24      Bjorn        NaN     Crathorne
24           25    Mariana   Ebenezer      Titmarsh
25           26     Clemmy        NaN        Widdup
26           27    Darrell       Egon        Lokier
27           28   Thornton        NaN      Kennaird
28           29     Philip    Jaquith     Edworthye
29           30        Dud        NaN      Harvison
..          ...        ...        ...           ...
970         971      Asher        NaN      Wasselin
971         972   Ninnetta      Vitia       Heasman
972         973   Cecilius        NaN       Popelay
973         974     Rhetta      Lisle    Hall-Gough
974         975   Elsinore        NaN       Cretney
975         976      Annis  Chevalier     Zum Felde
976         977     Merrel    Roberto      Sillwood
977         978        Boy      Reeva         Elwyn
978         979      Bryna        NaN        Vaskov
979         980       Brad   Sallyann         Clell
980         981     Salomi        NaN       Stockin
981         982        Der        NaN       Scarlan
982         983    Shannen       Anna      Purselow
983         984     Lilith  Alejandro  Childerhouse
984         985     Karita      Brice     Risbridge
985         986   Rosaline        NaN        Bowker
986         987       Joey        NaN          Burt
987         988    Marjory        NaN        Holgan
988         989      Adler      Urban         Beake
989         990        Jon      Danni        Bolley
990         991      Shawn        NaN      Whetland
991         992     Rhodie      Cross       Stovine
992         993   Raimondo        NaN       Hubbard
993         994     Darcey        NaN      Paolazzi
994         995     Carlos      Jessy        Barsam
995         996      Zared       Alan       Fontell
996         997     Janeta        NaN       Showers
997         998     Carlen        NaN        Bickle
998         999      Selie     Susana          Dahl
999        1000      Adina        NaN     Demougeot

[1000 rows x 4 columns]

In [7]:
name_df.to_csv('Contact.csv', index=False, encoding='utf-8')

In [8]:
cols = ['Contact_id', 'home_address', 'home_city', 'home_state', 'home_zip']
home_add_df = df.loc[:, cols]

In [9]:
home_add_df

     Contact_id                  home_address   home_city home_state  home_zip
0             1                           NaN         NaN        NaN   75018.0
1             2          2287 Sutteridge Park      Dallas      Texas   75062.0
2             3                           NaN         NaN        NaN   75029.0
3             4                           NaN         NaN        NaN   75099.0
4             5              62477 Hovde Hill       Allen      Texas   75061.0
5             6           06 Heffernan Center  Richardson      Texas       NaN
6             7                           NaN         NaN        NaN   75031.0
7             8               16515 Nova Hill       Allen      Texas   75041.0
8             9               626 Orin Center     Addison      Texas       NaN
9            10             6687 Dottie Plaza  Richardson      Texas   75027.0
10           11              8 Luster Terrace      Dallas      Texas   75059.0
11           12                           NaN         NaN        NaN   75076.0
12           13               15 Jackson Lane       Allen      Texas   75013.0
13           14             79254 Pond Center      Dallas      Texas   75083.0
14           15               9 Logan Parkway      Dallas      Texas   75078.0
15           16             65052 Heath Point       Plano      Texas   75046.0
16           17                           NaN         NaN        NaN   75005.0
17           18                 8 Fuller Road     Addison      Texas   75088.0
18           19            1961 Division Hill     Addison      Texas       NaN
19           20                           NaN         NaN        NaN   75042.0
20           21                           NaN         NaN        NaN   75060.0
21           22             528 Main Junction      Dallas      Texas   75046.0
22           23         9086 Sommers Crossing  Richardson      Texas       NaN
23           24                           NaN         NaN        NaN   75099.0
24           25           83 Shoshone Parkway       Plano      Texas   75046.0
25           26             333 Scoville Hill       Allen      Texas   75091.0
26           27           18894 Division Lane  Richardson      Texas   75083.0
27           28                 250 2nd Drive  Richardson      Texas       NaN
28           29              85701 Basil Road       Allen      Texas   75004.0
29           30                 23 Kings Lane       Plano      Texas   75086.0
..          ...                           ...         ...        ...       ...
970         971          5452 Walton Junction  Richardson      Texas   75074.0
971         972              22 Dwight Center     Addison      Texas   75033.0
972         973                   9 Kim Alley       Plano      Texas   75083.0
973         974           17 Killdeer Parkway     Addison      Texas   75087.0
974         975  70338 Clyde Gallagher Street      Dallas      Texas   75036.0
975         976              204 Caliangt Way      Dallas      Texas   75049.0
976         977                           NaN         NaN        NaN       NaN
977         978            7637 Burrows Alley     Addison      Texas   75085.0
978         979                           NaN         NaN        NaN   75001.0
979         980                0 Colorado Way  Richardson      Texas       NaN
980         981          07151 Anderson Trail       Allen      Texas   75079.0
981         982              0 Annamark Alley       Allen      Texas   75098.0
982         983                5 Coleman Lane      Dallas      Texas   75001.0
983         984               853 5th Terrace  Richardson      Texas       NaN
984         985        46789 Moulton Crossing     Addison      Texas   75099.0
985         986                           NaN         NaN        NaN       NaN
986         987               1 Thierer Drive  Richardson      Texas   75017.0
987         988                  7 Brown Hill     Addison      Texas   75077.0
988         989             8 Huxley Junction       Plano      Texas   75029.0
989         990           70 Del Mar Junction       Plano      Texas   75062.0
990         991      5228 Commercial Crossing       Allen      Texas       NaN
991         992       5 Blue Bill Park Street       Plano      Texas   75003.0
992         993            51469 Becker Point      Dallas      Texas   75014.0
993         994      583 Manufacturers Avenue  Richardson      Texas       NaN
994         995          0648 Lakewood Street       Plano      Texas   75006.0
995         996                   13 Main Way     Addison      Texas   75089.0
996         997       782 Lighthouse Bay Pass       Allen      Texas   75060.0
997         998               008 Ryan Center       Plano      Texas       NaN
998         999           5729 Farragut Plaza      Dallas      Texas   75079.0
999        1000           18201 Novick Circle  Richardson      Texas   75037.0

[1000 rows x 5 columns]

In [10]:
home_add_df.columns = ['Contact_id', 'Address', 'City', 'State', 'Zip']
home_add_df['Address_type'] = 'home'

In [11]:
home_add_df.to_csv('HomeAddress.csv', index=False, encoding='utf-8')

In [12]:
cols = ['Contact_id', 'work_address', 'work_city', 'work_state', 'work_zip']
work_add_df = df.loc[:, cols]

In [13]:
work_add_df.columns = ['Contact_id', 'Address', 'City', 'State', 'Zip']
work_add_df['Address_type'] = 'work'

In [14]:
work_add_df.to_csv('WorkAddress.csv', index=False, encoding='utf-8')

In [15]:
cols = ['Contact_id', 'birth_date']
date_df = df.loc[:, cols]

In [16]:
date_df.columns = ['Contact_id', 'Date']
date_df['Date_type'] = 'birthdate'

In [17]:
date_df.to_csv('Date.csv', index=False, encoding='utf-8')

In [18]:
cols = ['Contact_id', 'home_phone']
home_phone_df = df.loc[:, cols]

In [19]:
home_phone_df.columns = ['Contact_id', 'Number']
home_phone_df['Phone_type'] = 'home'
home_phone_df['Area_code'] = home_phone_df['Number']
home_phone_df['Contact_id'] = df['Contact_id']

In [20]:
for i in range(0, home_phone_df.shape[0]):
    #print(home_phone_df.iloc[i, 3])
    if home_phone_df.iloc[i, 3] == home_phone_df.iloc[i, 3]:
        areacode = home_phone_df.iloc[i, 3]
        areacode = str (areacode)[:3]
        home_phone_df.iloc[i, 3] = areacode
        ##print(home_phone_df.iloc[i, 3])
print(home_phone_df)

     Contact_id        Number Phone_type Area_code
0             1           NaN       home       NaN
1             2  441-557-2835       home       441
2             3  998-239-4082       home       998
3             4           NaN       home       NaN
4             5  317-756-0975       home       317
5             6           NaN       home       NaN
6             7           NaN       home       NaN
7             8           NaN       home       NaN
8             9           NaN       home       NaN
9            10  449-971-7759       home       449
10           11  790-832-4539       home       790
11           12  812-671-2569       home       812
12           13           NaN       home       NaN
13           14  454-730-8259       home       454
14           15           NaN       home       NaN
15           16  629-438-4169       home       629
16           17  804-209-6009       home       804
17           18           NaN       home       NaN
18           19           NaN       home       NaN
19           20           NaN       home       NaN
20           21           NaN       home       NaN
21           22  130-493-8381       home       130
22           23  234-782-3406       home       234
23           24  387-995-2640       home       387
24           25           NaN       home       NaN
25           26           NaN       home       NaN
26           27           NaN       home       NaN
27           28           NaN       home       NaN
28           29  388-488-7596       home       388
29           30  744-544-2543       home       744
..          ...           ...        ...       ...
970         971           NaN       home       NaN
971         972  236-716-1495       home       236
972         973           NaN       home       NaN
973         974  611-473-9520       home       611
974         975  118-808-6105       home       118
975         976  444-807-2663       home       444
976         977  189-943-3809       home       189
977         978  627-850-8581       home       627
978         979           NaN       home       NaN
979         980           NaN       home       NaN
980         981           NaN       home       NaN
981         982           NaN       home       NaN
982         983           NaN       home       NaN
983         984  164-120-1050       home       164
984         985           NaN       home       NaN
985         986           NaN       home       NaN
986         987           NaN       home       NaN
987         988  194-870-5733       home       194
988         989           NaN       home       NaN
989         990           NaN       home       NaN
990         991           NaN       home       NaN
991         992           NaN       home       NaN
992         993           NaN       home       NaN
993         994  597-896-7953       home       597
994         995  456-537-7814       home       456
995         996  121-713-2260       home       121
996         997  311-345-4648       home       311
997         998           NaN       home       NaN
998         999           NaN       home       NaN
999        1000  851-955-4193       home       851

[1000 rows x 4 columns]

In [21]:
home_phone_df.to_csv('HomePh.csv', index=False, encoding='utf-8')

In [22]:
cols = ['Contact_id', 'work_phone']
work_phone_df = df.loc[:, cols]
work_phone_df.columns = ['Contact_id', 'Number']
work_phone_df['Phone_type'] = 'work'
work_phone_df['Area_code'] = work_phone_df['Number']
work_phone_df['Contact_id'] = df['Contact_id']

In [23]:
for i in range(0, work_phone_df.shape[0]):
    #print(home_phone_df.iloc[i, 3])
    if work_phone_df.iloc[i, 3] == work_phone_df.iloc[i, 3]:
        areacode = work_phone_df.iloc[i, 3]
        areacode = str (areacode)[:3]
        work_phone_df.iloc[i, 3] = areacode
        ##print(home_phone_df.iloc[i, 3])
print(work_phone_df)

     Contact_id        Number Phone_type Area_code
0             1  575-780-6421       work       575
1             2  526-691-3663       work       526
2             3  470-347-7202       work       470
3             4           NaN       work       NaN
4             5  672-643-5210       work       672
5             6  935-221-4565       work       935
6             7           NaN       work       NaN
7             8  420-902-8960       work       420
8             9  536-596-8574       work       536
9            10  405-746-6553       work       405
10           11           NaN       work       NaN
11           12  974-398-8066       work       974
12           13           NaN       work       NaN
13           14           NaN       work       NaN
14           15  944-146-6149       work       944
15           16  100-718-3343       work       100
16           17           NaN       work       NaN
17           18  725-135-7813       work       725
18           19  373-829-6128       work       373
19           20  205-867-7790       work       205
20           21  136-209-9292       work       136
21           22  732-735-8158       work       732
22           23           NaN       work       NaN
23           24  364-839-7318       work       364
24           25  754-815-2133       work       754
25           26           NaN       work       NaN
26           27  205-324-5139       work       205
27           28  742-339-9060       work       742
28           29  570-895-9983       work       570
29           30           NaN       work       NaN
..          ...           ...        ...       ...
970         971  727-591-4194       work       727
971         972  474-611-4311       work       474
972         973  281-163-7057       work       281
973         974  513-590-6081       work       513
974         975  911-135-9814       work       911
975         976  725-849-3877       work       725
976         977  916-120-2308       work       916
977         978  680-399-1077       work       680
978         979  509-326-1544       work       509
979         980  885-458-7049       work       885
980         981  195-829-1027       work       195
981         982  153-854-4154       work       153
982         983           NaN       work       NaN
983         984  554-290-9935       work       554
984         985  935-280-2452       work       935
985         986           NaN       work       NaN
986         987  603-266-1070       work       603
987         988  998-707-5639       work       998
988         989           NaN       work       NaN
989         990           NaN       work       NaN
990         991  569-411-8436       work       569
991         992  914-785-8696       work       914
992         993           NaN       work       NaN
993         994  644-184-8850       work       644
994         995  929-545-6545       work       929
995         996  878-331-9664       work       878
996         997           NaN       work       NaN
997         998  266-423-8899       work       266
998         999  290-423-8165       work       290
999        1000           NaN       work       NaN

[1000 rows x 4 columns]

In [24]:
work_phone_df.to_csv('WorkPh.csv', index=False, encoding='utf-8')

In [25]:
cols = ['Contact_id', 'cell_phone']
cell_phone_df = df.loc[:, cols]
cell_phone_df.columns = ['Contact_id', 'Number']
cell_phone_df['Phone_type'] = 'cell'
cell_phone_df['Area_code'] = cell_phone_df['Number']
cell_phone_df['Contact_id'] = df['Contact_id']

In [26]:
for i in range(0, cell_phone_df.shape[0]):
    #print(home_phone_df.iloc[i, 3])
    if cell_phone_df.iloc[i, 3] == cell_phone_df.iloc[i, 3]:
        areacode = cell_phone_df.iloc[i, 3]
        areacode = str (areacode)[:3]
        cell_phone_df.iloc[i, 3] = areacode
        ##print(home_phone_df.iloc[i, 3])
print(cell_phone_df)

     Contact_id        Number Phone_type Area_code
0             1  732-392-7165       cell       732
1             2  907-913-3698       cell       907
2             3  637-715-3867       cell       637
3             4  359-747-1907       cell       359
4             5  543-710-0843       cell       543
5             6  227-992-2900       cell       227
6             7  181-781-9784       cell       181
7             8  871-791-7851       cell       871
8             9  933-257-7616       cell       933
9            10  747-303-4705       cell       747
10           11  423-257-0444       cell       423
11           12  537-987-3004       cell       537
12           13  994-189-5386       cell       994
13           14  223-746-7737       cell       223
14           15  769-740-9664       cell       769
15           16  275-477-5499       cell       275
16           17  272-367-4116       cell       272
17           18  770-282-5502       cell       770
18           19  131-155-6846       cell       131
19           20  452-967-2050       cell       452
20           21  310-517-1998       cell       310
21           22  905-442-0240       cell       905
22           23  886-702-1908       cell       886
23           24  562-617-1312       cell       562
24           25  873-511-6075       cell       873
25           26  826-297-4157       cell       826
26           27  770-453-6125       cell       770
27           28  806-105-9954       cell       806
28           29  899-522-4338       cell       899
29           30  993-228-0137       cell       993
..          ...           ...        ...       ...
970         971  350-773-0890       cell       350
971         972  805-597-6743       cell       805
972         973  338-961-3558       cell       338
973         974  501-940-1523       cell       501
974         975  684-423-9257       cell       684
975         976  213-779-9815       cell       213
976         977  814-757-2525       cell       814
977         978  722-225-7767       cell       722
978         979  727-717-8575       cell       727
979         980  603-661-8661       cell       603
980         981  584-623-3883       cell       584
981         982  133-729-1440       cell       133
982         983  404-917-0949       cell       404
983         984  559-290-1726       cell       559
984         985  882-789-1124       cell       882
985         986  643-101-9733       cell       643
986         987  713-594-7295       cell       713
987         988  984-335-4433       cell       984
988         989  916-995-4675       cell       916
989         990  125-555-5586       cell       125
990         991  315-727-4644       cell       315
991         992  630-956-5252       cell       630
992         993  871-510-0110       cell       871
993         994  281-491-8104       cell       281
994         995  499-711-1417       cell       499
995         996  511-907-3315       cell       511
996         997  273-728-1271       cell       273
997         998  220-911-1306       cell       220
998         999  470-418-2608       cell       470
999        1000  952-976-4138       cell       952

[1000 rows x 4 columns]

In [27]:
cell_phone_df.to_csv('CellPh.csv', index=False, encoding='utf-8')